# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='mapid',
        ),
    ]
