# Generated by Django 5.1.2 on 2024-10-14 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth2Applications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uris', models.TextField()),
                ('confidential', models.BooleanField()),
                ('permission_read_prefs', models.BooleanField()),
                ('permission_write_prefs', models.BooleanField()),
                ('permission_write_diary', models.BooleanField()),
                ('permission_write_api', models.BooleanField()),
                ('permission_read_gpx', models.BooleanField()),
                ('permission_write_gpx', models.BooleanField()),
                ('permission_write_notes', models.BooleanField()),
                ('permission_write_redactions', models.BooleanField()),
                ('permission_consume_messages', models.BooleanField()),
                ('permission_send_messages', models.BooleanField()),
                ('permission_openid', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oauth2Authorizations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission_read_prefs', models.BooleanField()),
                ('permission_write_prefs', models.BooleanField()),
                ('permission_write_diary', models.BooleanField()),
                ('permission_write_api', models.BooleanField()),
                ('permission_read_gpx', models.BooleanField()),
                ('permission_write_gpx', models.BooleanField()),
                ('permission_write_notes', models.BooleanField()),
                ('permission_write_redactions', models.BooleanField()),
                ('permission_consume_messages', models.BooleanField()),
                ('permission_send_messages', models.BooleanField()),
                ('permission_openid', models.BooleanField()),
                ('parent_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth2.oauth2applications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='oauth2applications',
            index=models.Index(fields=['user'], name='oauth2_app_client_id_idx'),
        ),
        migrations.AddIndex(
            model_name='oauth2applications',
            index=models.Index(fields=['user'], name='oauth2_app_user_idx'),
        ),
        migrations.AddIndex(
            model_name='oauth2authorizations',
            index=models.Index(fields=['parent_app'], name='oauth2_auth_parent_app_idx'),
        ),
        migrations.AddIndex(
            model_name='oauth2authorizations',
            index=models.Index(fields=['user'], name='oauth2_auth_user_idx'),
        ),
    ]
