# Generated by Django 5.1.2 on 2024-10-14 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oauth2Applications',
            new_name='Oauth2Application',
        ),
        migrations.RenameModel(
            old_name='Oauth2Authorizations',
            new_name='Oauth2Authorization',
        ),
    ]
