# Generated by Django 5.1.2 on 2024-10-14 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0002_rename_oauth2applications_oauth2application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauth2application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oauth2authorization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauth2authorization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
