# Generated by Django 5.1.2 on 2024-10-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0003_oauth2application_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2application',
            name='disabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauth2authorization',
            name='disabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
