#Based on https://micropyramid.com/blog/setting-up-travis-ci-for-django-project/
sudo: required
dist: trusty
language: python
python:
  - "2.7"

services:
  - postgresql

env:
  - DJANGO=1.11

install:
  - pip install -r requirements.txt

before_script:
  - sudo apt update
  - sudo apt install -y libpqxx-dev libexpat1-dev python-pip swig3.0 libboost-filesystem-dev libboost-program-options-dev
  - wget https://github.com/Tencent/rapidjson/archive/v1.1.0.tar.gz
  - tar -xvf v1.1.0.tar.gz
  - cd rapidjson-1.1.0
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - cd ../..
  - cd pgmap
  - sudo python setup.py install
  - make
  - cd ..

script:
  - python manage.py test

