#Based on https://micropyramid.com/blog/setting-up-travis-ci-for-django-project/
language: python
python:
  - "2.7"

services:
  - postgresql

env:
  - DJANGO=1.11

install:
  - pip install -r requirements.txt

before_script:
  - uname -a
  - cat /etc/issue
  - sudo apt update
  - sudo apt install -y libpqxx-dev rapidjson-dev libexpat1-dev python-pip swig3.0 libboost-filesystem-dev libboost-program-options-dev
  - cd pgmap
  - python setup.py install
  - make
  - cd ..

script:
  - python manage.py test

