#Based on https://micropyramid.com/blog/setting-up-travis-ci-for-django-project/
language: python
python:
  - "2.7"

services:
  - postgresql

env:
  - DJANGO=1.11

install:
  - pip install -r requirements.txt

before_script:
  - sudo apt install libpqxx-dev rapidjson-dev libexpat1-dev python-pip swig3.0 libboost-filesystem-dev libboost-program-options-dev
  - python setup.py install
  - 
#  - mysql -e 'create database test;' -u root

script:
  - python manage.py test

