version: '3.7'

services:
  web:
    build: ./
    command: python3 manage.py runserver 0.0.0.0:8000
    #command: /opt/env/bin/python3 manage.py migrate
    #command: sleep infinity
    #command: gunicorn pycrocosm.wsgi:application --bind 0.0.0.0:8000 -w 2
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

