# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAccount',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(max_length=255)),
                ('created_at', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('zoom', models.IntegerField()),
            ],
        ),
    ]
