# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0003_auto_20170905_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='bbox_set',
            field=models.BooleanField(default=False),
        ),
    ]
