# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
