# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170905_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='home_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='home_lon',
            field=models.FloatField(default=0.0),
        ),
    ]
